[package]
name = "http-tarpit"
version = "0.1.0"
edition = "2018"
authors = ["Vsevolod Stakhov <vsevolod@highsecure.ru>"]
description = "tarpit endpoint for HTTP requests"
repository = "https://github.com/vstakhov/http-tarpit"
readme = "README.md"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8"
futures = "0.3"
log = "0.4"
structopt = "0.3"
tokio = { version = "1.11", features = ["io-util", "macros", "net", "rt", "signal", "sync", "time"] }
tokio-stream = { version = "0.1.7", features = ["net", "time"] }
async-stream = "0.3.0"

[target."cfg(unix)".dependencies]
privdrop = { version = "0.5", optional = true }
libc = "0.2"

[features]
default = ["drop_privs"]
drop_privs = ["privdrop"]